// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37cy0q-Iz5aNy1mXGKqc19iqK5NOhBNI',
    appId: '1:962590420817:web:0b6a5642f6193b86562d70',
    messagingSenderId: '962590420817',
    projectId: 'aquafeed-3391d',
    authDomain: 'aquafeed-3391d.firebaseapp.com',
    storageBucket: 'aquafeed-3391d.appspot.com',
    measurementId: 'G-EXKD6WFXBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDChr9__HkBMEWclaAyRsTcz-4S386Yyr8',
    appId: '1:962590420817:android:ce7e720910457db1562d70',
    messagingSenderId: '962590420817',
    projectId: 'aquafeed-3391d',
    storageBucket: 'aquafeed-3391d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp_esKADiG7IHs_YSOh0N_VCMcQwQyv00',
    appId: '1:962590420817:ios:db768010c388f0fb562d70',
    messagingSenderId: '962590420817',
    projectId: 'aquafeed-3391d',
    storageBucket: 'aquafeed-3391d.appspot.com',
    iosBundleId: 'com.example.aquafeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp_esKADiG7IHs_YSOh0N_VCMcQwQyv00',
    appId: '1:962590420817:ios:b1bd5c6ea8251b41562d70',
    messagingSenderId: '962590420817',
    projectId: 'aquafeed-3391d',
    storageBucket: 'aquafeed-3391d.appspot.com',
    iosBundleId: 'com.example.aquafeed.RunnerTests',
  );
}
